site_name: Cloud Engineer course
nav:
  - Table of contents: index.md
  - Module 1 - Advanced Programming & Best Practices: 
    - Chapter 1 - (Python) Language Deep Dive & Idiomatic Code:
      - Content: module_1/chapter_1.md
      - Quiz: module_1/chapter_1_quiz.md
      - Exercises: module_1/chapter_1_exercise.md
theme: 
  name: material
markdown_extensions:
 - admonition
 - pymdownx.superfences
 - pymdownx.details